In [23]:
#⚠️
#Si en algún momento no sabés dónde estás parada, !pwd te dice la carpeta actual. Tiene que mostrar /content/grupo_Luabre.

#⚠️⚠️
#-------
#!python pipeline_tfidf.py --datos data/rd --alphas 0 0.5
#--------

#Esta celda corre tu pipeline como archivo .py,
#igual que si lo ejecutaras desde una terminal, y no usa las variables del notebook.
# Calcula todo desde cero (carga los datos, ajusta TF-IDF, puntúa, rankea y evalúa), pero solo para alpha = 0 y alpha = 0,5.

#Sirve para comprobar que el ejecutable da lo mismo que las celdas del notebook.
#No hace falta correrla todos los días.
#Correla cuando modifiques pipeline_tfidf.py o antes de una entrega,
#porque esa es la prueba de que el ejecutable funciona solo. Hoy podés saltearla.

#si la corrés, tiene que ser después de la celda 1,
#porque necesita estar en la carpeta del repo. Genera archivos rank_rd_alpha*.csv, que Git ignora.

#⚠️⚠️⚠️
#-----------
#!git status --short
#-------------
#Es el archivo que crean las celdas 6 y 13. .gitignore no cubre los .parquet, así que Git lo marca como nuevo. Los .csv, data/ y __pycache__
#no aparecen porque sí están ignorados. Que aparezca ese archivo es normal y no pasa nada mientras no lo agregues con git add.

#No hace falta correrla todos los días.
#Es la que usás antes de un commit, para ver qué vas a subir. Dejala si querés, pero no te cambia nada en la rutina.
#⚠️⚠️⚠️⚠️
#---------------
# SUBIR CAMBIOS A GITHUB (cambiar archivos y mensaje cada vez)
#import base64
#from google.colab import userdata
#%cd /content/grupo_Luabre
#tok = userdata.get("GH_TOKEN")
#h = base64.b64encode(f"x-access-token:{tok}".encode()).decode()

#!git add NOMBRE_DEL_ARCHIVO OTRO_ARCHIVO
#!git status --short
#!git commit -m "Descripción corta de lo que cambió"
#!git -c http.extraheader="Authorization: Basic {h}" push origin main
#!git status -sb | head -1

In [1]:
#1
# CORRER SIEMPRE PRIMERO: levanta el repo, los datos y las librerias
import base64
from google.colab import userdata
tok = userdata.get("GH_TOKEN")
h = base64.b64encode(f"x-access-token:{tok}".encode()).decode()

username = "AbiFrei"
repo = "grupo_Luabre"

!git config --global user.name "Abigail Freijomil"
!git config --global user.email "larvas@protonmail.com"

%cd /content
!test -d {repo} || git -c http.extraheader="Authorization: Basic {h}" clone https://github.com/{username}/{repo}.git
%cd /content/{repo}
!git remote add upstream https://github.com/bravoivanagustin/ranking-licitaciones.git 2>/dev/null

!test -d data || (wget -q https://github.com/bravoivanagustin/ranking-licitaciones/releases/download/datos-v1/data.zip && unzip -q data.zip)
!pip -q install pandas pyarrow scikit-learn
!python b0.py data/rd --salida b0_rd.csv
!ls
!git log --oneline | head -3

/content
Cloning into 'grupo_Luabre'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 29 (delta 13), reused 24 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (29/29), 121.34 KiB | 2.70 MiB/s, done.
Resolving deltas: 100% (13/13), done.
/content/grupo_Luabre
328 licitaciones -> b0_rd.csv
b0.py	   data.zip		 pipeline_tfidf.py  resultados.md
b0_rd.csv  evaluar.py		 pyproject.toml     uv.lock
data	   exploracion_rd.ipynb  README.md
fcff492 Experimentación iii: SVD
e90dfb6 Experimentación ii (lematizar y raíz) y nombres unificados en resultados.md
a768001 Experimento 2: validación cronológica selección 2023 / prueba 2024S1

In [2]:
#2
import pandas as pd

#---
import sys; sys.path.append(".")          # para poder hacer "import b0"
import subprocess
import numpy as np, pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import b0

In [28]:
#esta celda es la configuración inicial, la que se usaba una sola vez al principio
#para crear el repo a partir del de la cátedra. Eso ya está hecho: tu repo existe y tiene tu trabajo. Si la corrés de nuevo, vuelve a clonar el repo de la cátedra con el nombre grupo_Luabre y trata de subirlo encima de tu repo. Por eso falló antes."
#from google.colab import userdata
#tok = userdata.get("GH_TOKEN")

#username = "AbiFrei"   # cambiar
#repo = "grupo_Luabre"                    # cambiar: el nombre exacto del paso 1

#!git config --global user.name "Abigail Freijomil"          # cambiar
#!git config --global user.email "larvas@protonmail.com"   # cambiar

#!git clone https://github.com/bravoivanagustin/ranking-licitaciones.git {repo}
#%cd {repo}
#!git remote rename origin upstream
#!git remote add origin https://{tok}@github.com/{username}/{repo}.git
#!git push -u origin main'''

In [3]:
#3
#primera inspeccion　para ver que coincide con el README, antes de usar los datos
#no hace falta correr siempre esta celda, es solo un checkeo para poder arrancar
V = "rd"   # la vertical mas chica

lic  = pd.read_parquet(f"data/{V}/licitaciones.parquet")
gan  = pd.read_parquet(f"data/{V}/ganadores.parquet")
emp  = pd.read_parquet(f"data/{V}/empresas.parquet")
hist = pd.read_parquet(f"data/{V}/historial.parquet")

for nombre, df in [("licitaciones", lic), ("ganadores", gan), ("empresas", emp), ("historial", hist)]:
    print("=====", nombre, df.shape)
    print(list(df.columns))
    display(df.head(2)) #para ver filas al azar en lugar de las primeras, usar df.sample(3), que muestra 3 filas elegidas al azar cada vez.

    #me va a devolver algo de la pinta licitaciones (328, 8)→ (filas, columnas)
    #La lista de nombres son las columnas.

===== licitaciones (328, 8)
['id', 't', 'title', 'description', 'psc', 'naics', 'office', 'set_aside']

,id,t,title,description,psc,naics,office,set_aside
0,HQ085022R0002,2022-01-03,SDA Tranche 1 Operations & Integration (O&I),The Space Development Agency (SDA) is issuing ...,AC33,541715,HQ0850,
1,FA875020S7019,2022-01-03,"LOW SIZE, WEIGHT AND POWER (SWaP), CROSS-DOMAI...",NAICS CODE: 541715 FEDERAL AGENCY NAME: Depart...,AC12,541715,FA8750,

===== ganadores (541, 2)
['id', 'parent_uei']

              id    parent_uei
0  123A9422R0013  JJHCMK4NT5N3
1  12405B23Q0317  KVLBRRAQ6UX1

===== empresas (60599, 5)
['parent_uei', 'semestre', 'name', 'n_awards', 'texto_awards']

,parent_uei,semestre,name,n_awards,texto_awards
0,C116E6T5MGD6,2022S1,MARZEN GROUP LLC,1,TDACS HELPDESK SUPPORT - BASE YEAR
1,C11MNATAJ3K5,2022S1,UNIVERSITY OF ILLINOIS,1,SCREENING OF SOYBEAN LINES FOR SCN RESISTANCE

===== historial (84835, 7)
['fecha', 'parent_uei', 'psc', 'naics', 'office', 'set_aside', 'descripcion']

,fecha,parent_uei,psc,naics,office,set_aside,descripcion
0,2002-08-02,JDKYAKDT4TT6,AD93,,,,IGF::CL::IGF A ROBUST HEAT EXCHANGER FOR AS TU...
1,2009-08-19,RKQ9JU484A29,AR11,,,,CITY AIR MOBILITY EVALUATION OPERATIONS SUITE

In [4]:
#4 leer el texto para verificar que esta "leyendo" TF-IDF
pd.set_option("display.max_colwidth", 400)

# 1) cuatro perfiles de ejemplo, con su largo
ej = emp.sample(4, random_state=0)
for _, f in ej.iterrows(): #para recorrer las cuatro filas
    print(f"{f['name']} | {f['semestre']} | n_awards={f['n_awards']} | largo del texto={len(str(f['texto_awards']))}")
    print(str(f['texto_awards'])[:400])
    print("-----")

# 2) ¿cuántas empresas tienen el texto vacío?
print("textos vacíos:", emp['texto_awards'].isna().sum() + (emp['texto_awards'] == "").sum())
#Importa porque una empresa sin texto no tiene nada que comparar: su similitud de texto va a ser siempre 0, y el modelo solo puede juzgarla por el B0.

# 3) una licitación completa (no recortada)
print(lic.iloc[0]['title'])
print(lic.iloc[0]['description'])

ALABAMA DEPARTMENT OF PUBLIC HEALTH | 2022S2 | n_awards=1 | largo del texto=29
MODIFICATION VSCP TASKS ORDER
-----
CLOUDBURST CONSULTING GROUP, INC. | 2023S2 | n_awards=1 | largo del texto=250
THE PRIMARY PURPOSE OF THIS TASK IS TO CONDUCT AN ANALYSIS OF BIODIVERSITY CONSERVATION NEEDS IN MOLDOVA IN ORDER TO COMPLY WITH SECTIONS 118 AND 119 OF THE FOREIGN ASSISTANCE ACT OF 1961, AS AMENDED AND COUNTRY STRATEGY GUIDELINES UNDER ADS 201.3.4.
-----
MR TECHNICAL SPECIALISTS LLC | 2022S2 | n_awards=1 | largo del texto=21
HPLC REPAIRS SERVICES
-----
VELOXAI LLC | 2024S1 | n_awards=1 | largo del texto=117
PROJECT TITLE: AUTOMATIC TREATMENT PLANNING OF CERVICAL CANCER HIGH-DOSE RATE BRACHYTHERAPY FOR LOW-RESOURCE SETTINGS
-----
textos vacíos: 1524
SDA Tranche 1 Operations & Integration (O&I)
The Space Development Agency (SDA) is issuing this pre-solicitation notice to establish the ground operations and integration segment for Tranche 1 (T1), the Initial Warfighting Capability Tranche, of the National Defense Space Architecture (NDSA). The NDSA s operational utility is predicated on the availability of a ubiquitous data and communications Transport Layer provided by a proliferated constellation of relatively small, mass-producible space vehicles (SVs) in low Earth orbit (LEO). SDA is seeking Operations and Integration (O&I) support for the T1TL constellation as well as future capability layers and tranches from two redundant, geographically seprated, and potentially Government owned and Contractor operated (GOCO) operation centers. The Contractor will demonstrate the capabilities to manage, operate, maintain, and provide logistical and general support for the T1 O&I. Estimated Acquisition Timeline: Final RFP Release: EST January 18, 2022 Technical Proposal Due: EST Feburary 24, 2022 Cost Proposal Due: EST March 3, 2022 Contract Award: EST June 24, 2022 The above acquisition timeline is for informational purposes only and subject to change. Questions regarding this requirement shall ONLY be submitted to osd.pentagon.ousd-r-e.mbx.hq085022r0002@mail.mil. No phone calls or one-on-one meeting requests will be accepted. DO NOT submit classified information to this email address.

In [5]:
#5
#Esto es para reproducir el baseline (B0)→checkeo que todo de como me lo indican  (prueba para ver que el entorno funciona)
!python evaluar.py b0_rd.csv --datos data/rd # compara cada ranking con la tabla de ganadores

conjunto   N   MRR  Hit@5  Hit@1  Hit@100  Recall@100  puesto mediano
   todas 328 0.125  0.271  0.079    0.628       0.532           9.000

###Bueno hasta aca ↑↑↑ Es el B0 y se corrio lo que nos proporcionaron de base. Exito.

###Cómo leer el resultado
Hit@1 = 0,079: solo en el 8% de las licitaciones el B0 pone a un ganador en el primer puesto.

Hit@5 = 0,271: en el 27% hay un ganador entre los primeros 5.

Hit@100 = 0,628: en el 63% hay algún ganador dentro de las 100 empresas del ranking. En el 37% restante el B0 no tiene a ningún ganador en su lista. Ahí no hay nada que reordenar: solo el texto puede traer a esos ganadores de más abajo, y ese es el espacio de mejora más grande.

Recall@100 = 0,532: es menor que Hit@100 porque algunas licitaciones tienen varios ganadores y el B0 no los trae a todos.

Puesto mediano = 9: cuando el B0 sí incluye un ganador, el mejor está en mediana en el puesto 9.

In [7]:
#(i)
#Esto es para entender mejor texto_awards
emp["largo"] = emp["texto_awards"].fillna("").str.len()
print(emp["n_awards"].describe())
print(emp.groupby(emp["n_awards"].clip(upper=10))["largo"].median())   # largo mediano según n_awards

# una empresa con varios contratos: ¿el texto coincide con su historial?
f = emp[emp.n_awards >= 3].sample(1, random_state=1).iloc[0]
print(f["name"], f["semestre"], "n_awards =", f["n_awards"])
print("TEXTO_AWARDS:", f["texto_awards"][:600])

ini = pd.Timestamp(int(f["semestre"][:4]), 1 if f["semestre"].endswith("S1") else 7, 1)
h = hist[(hist.parent_uei == f["parent_uei"]) & (pd.to_datetime(hist.fecha) < ini)]
print("\nHISTORIAL antes del semestre:", len(h), "contratos")
print(h.sort_values("fecha").tail(5)[["fecha", "descripcion"]].to_string())

count    60599.000000
mean         5.120646
std         23.820029
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max       1556.000000
Name: n_awards, dtype: float64
n_awards
1       50.0
2      130.0
3      203.0
4      301.0
5      357.5
6      432.5
7      505.0
8      601.0
9      684.0
10    1709.0
Name: largo, dtype: float64
COTTLE JACQULINE L 2023S2 n_awards = 3
TEXTO_AWARDS: RESEARCH SUPPORT TO COMPLETE REPORT | RESEARCH SUPPORT | ARCSAR RESEARCH SERVICE CONTRACT

HISTORIAL antes del semestre: 3 contratos
           fecha                          descripcion
26801 2019-09-05     ARCSAR RESEARCH SERVICE CONTRACT
33196 2020-09-01                     RESEARCH SUPPORT
41476 2022-01-25  RESEARCH SUPPORT TO COMPLETE REPORT

####nota:
texto_awards ya es el perfil de cada empresa. En el ejemplo, el texto era exactamente las descripciones de sus 3 contratos anteriores, unidas con | y con el más reciente primero. No hace falta armarlo desde historial.
La mayoría de las empresas tiene pocos contratos (mediana 1, tres cuartos tienen 3 o menos), y unas pocas tienen cientos. El texto va de unos 50 caracteres con 1 contrato a más de 1.700 con 10 o más.
b0.py tiene lo que necesitamos: una clase B0 con p_b0(lic, empresas), que devuelve un puntaje por empresa, además de ranking() y candidatas().

In [6]:
#6
# Mi validacion y el B0 sobre ella

val = lic[lic.t >= "2024-01-01"]
print("licitaciones de validación:", len(val))
gan[gan.id.isin(val.id)].to_parquet("mi_val_rd.parquet")

!python evaluar.py b0_rd.csv --datos data/rd --respuestas mi_val_rd.parquet
!grep -n "def \|class " b0.py

#Esto es nuestra validación
# (57 licitaciones de enero a junio de 2024) o sea estas son las licitaciones que uso para validar,
#donde el B0 da MRR 0,091, Hit@5 0,228 y Hit@1 0,053. Ese es el número a superar.

##ese 0,091 (junto con Hit@5 0,228 y Hit@1 0,053) es la vara contra la que se compara todo lo que pruebes.

licitaciones de validación: 57
conjunto  N   MRR  Hit@5  Hit@1  Hit@100  Recall@100  puesto mediano
   todas 57 0.091  0.228  0.053    0.491       0.409           7.000
51:def set_aside(s) -> str:
61:def semestre(t) -> str:
67:def candidatas(empresas: pd.DataFrame, t) -> np.ndarray:
77:class B0:
80:    def __init__(self, historial: pd.DataFrame):
97:    def _indexar(self, cols: tuple) -> dict:
109:    def _p(self, lic) -> np.ndarray:
126:    def p_b0(self, lic, empresas: pd.DataFrame | None = None) -> pd.Series:
134:    def ranking(self, lic, empresas: pd.DataFrame, top: int = 100) -> pd.DataFrame:
145:def main() -> None:

## experimentacion 0
## Pipeline 1: B0 + TF-IDF

La idea: para cada licitación, a cada empresa candidata le calculamos dos números (p, que sale del B0, y sim, la similitud de texto), los mezclamos con un peso alpha, y nos quedamos con las 100 mejores. Cada bloque va en una celda distinta.

In [7]:
#7#
#preparación
# define la fecha de corte, la función que convierte una fecha en semestre (2024-03-15 → 2024S1) y la validación (val, 57 licitaciones).
CORTE = "2024-01-01"      # desde acá es validación; lo anterior es "pasado"

def semestre_de(t):
    t = pd.Timestamp(t)
    return f"{t.year}S{1 if t.month <= 6 else 2}"

val = lic[lic.t >= CORTE].copy()
print("licitaciones de validación:", len(val)) #crea una tabla independiente, para que modificar val no toque lic.

licitaciones de validación: 57

In [8]:
#8#
# dos chequeos antes de modelar

# a) las ganadoras de validacion estan entre las candidatas de su semestre?
sem_val = val["t"].map(semestre_de)
cand_por_sem = {s: set(emp.loc[emp.semestre == s, "parent_uei"]) for s in sem_val.unique()}
gv = gan[gan.id.isin(val.id)].merge(val[["id", "t"]], on="id")
gv["es_candidata"] = [u in cand_por_sem[semestre_de(t)] for u, t in zip(gv.parent_uei, gv.t)]
print("ganadores de validación:", len(gv), "| que son candidatas:", round(gv.es_candidata.mean(), 3))

# b) construir el B0 y probarlo sobre UNA licitacion
prior = b0.B0(hist.copy())      # .copy() protege a hist, que se usa en la celda 9
q = val.iloc[0]
cand = emp[emp.semestre == semestre_de(q["t"])]
p = prior.p_b0(q, cand)
print(type(p), len(p), "| empresas con p > 0:", int((p > 0).sum()))
print(p.sort_values(ascending=False).head(5))

# a) da 1.0 por construcción: se saco (o sea ya me lo dieron asi) del dataset a las ganadoras que no eran
#     candidatas. Confirma que los datos estan bien, ((pero no es un hallazgo.
# b) confirma que sabemos llamar al B0. Le da puntaje > 0 a las 13.880 candidatas.
# Esta celda crea "prior", que usa la celda 11.

ganadores de validación: 87 | que son candidatas: 1.0
<class 'pandas.core.series.Series'> 13880 | empresas con p > 0: 13880
KECGGH9MU4C9    0.086197
NUDGYLBB4S99    0.058385
RWWNRZQT5AQ4    0.057502
ZL41ERXMPAR3    0.041859
FTMTDMBR29C7    0.030149
dtype: float64

In [9]:
#9#
# aprender el vocabulario de TF-IDF

textos_pasado = hist.loc[pd.to_datetime(hist.fecha) < CORTE, "descripcion"].fillna("")
tfidf = TfidfVectorizer(lowercase=True, stop_words="english", ngram_range=(1, 2),
                        min_df=2, max_features=100_000, sublinear_tf=True)
tfidf.fit(textos_pasado)
print("palabras/frases en el vocabulario:", len(tfidf.vocabulary_))

# Aprende solo con contratos anteriores al corte, para no usar información del futuro.
# Usa historial porque es el mismo tipo de texto con el que se arman los perfiles (texto_awards).
# lowercase=True: texto_awards viene en MAYÚSCULAS y las licitaciones mezclan; se pasa todo a minúsculas.
# stop_words="english": descarta palabras vacías ("the", "of").
# ngram_range=(1, 2): usa palabras sueltas y pares ("health care").
# min_df=2: ignora términos que aparecen en un solo contrato.
# max_features=100_000: se queda con los 100.000 términos más frecuentes (por eso da exacto 100000).
# sublinear_tf=True: usa 1 + log(repeticiones), para que una palabra repetida muchas veces no domine.
# Por defecto cada vector sale con largo 1 (norma L2): por eso en la celda 11 el coseno
# es una simple multiplicación.

palabras/frases en el vocabulario: 100000

In [10]:
#10#

#  el perfil de cada empresa, convertido a números
# que hace? para cada semestre de validacion,
#           toma a las candidatas y convierte su texto_awards en vectores con el vocabulario
#           de la #9. Queda una matriz de 13.880 empresas × 100.000 terminos.

#Criterio: los perfiles se calculan una sola vez por semestre y no una vez por licitacion,
#          porque las 57 licitaciones comparten las mismas candidatas. Ahorra mucho tiempo.
#          reset_index(drop=True) hace que la fila 0 de la tabla coincida con la fila 0 de la matriz.

perfiles = {}
for s in sorted(val["t"].map(semestre_de).unique()):
    cand = emp[emp.semestre == s].reset_index(drop=True)
    perfiles[s] = (cand, tfidf.transform(cand["texto_awards"].fillna("")))
    print(s, "| candidatas:", len(cand), "| matriz:", perfiles[s][1].shape)

# Una matriz por semestre (se calcula una vez y la usan todas las licitaciones de ese semestre).
# reset_index(drop=True): la fila i de cand coincide con la fila i de la matriz.
# Las empresas con texto vacío (2,5%) quedan con un vector de ceros: similitud 0.

2024S1 | candidatas: 13880 | matriz: (13880, 100000)

In [11]:
#11#
#  los dos puntajes por licitación

def txt(x):
    return "" if pd.isna(x) else str(x)

scores = {}
for _, q in val.iterrows():
    cand, M = perfiles[semestre_de(q["t"])]
    p = prior.p_b0(q, cand).reindex(cand["parent_uei"]).fillna(0).to_numpy()
    v = tfidf.transform([txt(q["title"]) + " " + txt(q["description"])])
    sim = (M @ v.T).toarray().ravel()          # similitud coseno con cada empresa
    scores[q["id"]] = (cand["parent_uei"].to_numpy(), p, sim, v)   # ahora guarda también v
print("licitaciones puntuadas:", len(scores))


#----como funciona esto:------
'''Qué hace: para cada una de las 57 licitaciones calcula,
             para todas las candidatas:

p: el puntaje del B0. reindex(...) lo pone en el mismo orden que la matriz,
   y fillna(0) le da 0 a cualquier candidata que el B0 no haya puntuado.

v: el vector del título más la descripción de la licitación.

sim: el coseno entre la licitación y cada empresa.
     M @ v.T multiplica la matriz de empresas por el vector de la licitación,
     y como todos los vectores tienen largo 1, el resultado es directamente el coseno.

Criterio: guardar los puntajes por separado y sin mezclar,
          así se puede probar muchos alpha en la #13 sin recalcular nada.
          v se guarda para poder inspeccionar casos (las celdas de prueba lo usan).'''

licitaciones puntuadas: 57

'Qué hace: para cada una de las 57 licitaciones calcula, \n             para todas las candidatas:\n\np: el puntaje del B0. reindex(...) lo pone en el mismo orden que la matriz, \n   y fillna(0) le da 0 a cualquier candidata que el B0 no haya puntuado.\n\nv: el vector del título más la descripción de la licitación.\n\nsim: el coseno entre la licitación y cada empresa.\n     M @ v.T multiplica la matriz de empresas por el vector de la licitación,\n     y como todos los vectores tienen largo 1, el resultado es directamente el coseno.\n\nCriterio: guardar los puntajes por separado y sin mezclar, \n          así se puede probar muchos alpha en la #13 sin recalcular nada. \n          v se guarda para poder inspeccionar casos (las celdas de prueba lo usan).'

In [12]:
#12#
#  mezclar y rankear

def norm(x):
    m = x.max()
    return x / m if m > 0 else x

def armar_ranking(alpha, top=100, seed=0):
    rng = np.random.default_rng(seed)
    filas = []
    for lid, (ids, p, sim, v) in scores.items():
        s = norm(p) + alpha * norm(sim) + 1e-9 * rng.random(len(p))   # el ruido solo desempata
        for puesto, i in enumerate(np.argsort(-s)[:top], 1):
            filas.append((lid, ids[i], puesto))
    return pd.DataFrame(filas, columns=["id", "parent_uei", "puesto"])

# norm: divide cada puntaje por su máximo dentro de la licitación, así B0 y texto quedan entre 0 y 1. (el mejor vale 1).
# alpha: cuánto pesa el texto. 0 = B0 puro; 1 = pesan igual.
# armar_ranking suma norm(p) + alpha × norm(sim), ordena de mayor a menor (argsort(-s)), se queda con las 100 primeras y les asigna puesto
# El ruido (0,000000001) solo desempata a empresas con exactamente el mismo puntaje
# (por ejemplo, las de texto vacío); con seed=0 el desempate es siempre el mismo.

In [13]:
#13#
#  evaluar varios valores de alpha, contra el B0 y en una sola tabla
import evaluar as ev    # el evaluador que me dieron, usado como módulo (mismas métricas)

gan_val = gan[gan.id.isin(val.id)]                 # las respuestas de la validación
rk_b0 = pd.read_csv(f"b0_{V}.csv")                 # el ranking del B0 (lo genera la celda 1)
rk_b0 = rk_b0[rk_b0.id.isin(val.id)]               # solo las licitaciones de validación

filas = []
for a in [0, 0.1, 0.25, 0.5, 1, 2]:
    rk = armar_ranking(a)
    rk.to_csv(f"rank_{V}_alpha{a}.csv", index=False)
    res = ev.evaluar(rk, lic, emp, gan_val, rk_b0)
    f = res[res.conjunto == "todas"].iloc[0]
    filas.append({"alpha": a, "MRR": f["MRR"], "Hit@5": f["Hit@5"], "Hit@1": f["Hit@1"],
                  "Δ MRR vs B0": f["Δ MRR"], "IC95 del Δ": f["Δ MRR IC95"],
                  "Hit@100": f["Hit@100"], "Recall@100": f["Recall@100"],
                  "puesto mediano": f["puesto mediano"]})

tabla = pd.DataFrame(filas)
with pd.option_context("display.float_format", "{:.3f}".format):
    display(tabla)

,alpha,MRR,Hit@5,Hit@1,Δ MRR vs B0,IC95 del Δ,Hit@100,Recall@100,puesto mediano
0,0.000,0.091,0.228,0.053,0.000,"(+0.000, +0.000)",0.491,0.409,7.000
1,0.100,0.106,0.228,0.070,0.015,"(+0.002, +0.040)",0.526,0.462,7.500
2,0.250,0.110,0.246,0.070,0.019,"(+0.004, +0.046)",0.544,0.470,8.000
3,0.500,0.114,0.246,0.070,0.024,"(+0.004, +0.052)",0.526,0.456,8.000
4,1.000,0.112,0.228,0.070,0.021,"(-0.008, +0.056)",0.509,0.443,6.000
5,2.000,0.097,0.158,0.053,0.006,"(-0.060, +0.076)",0.474,0.398,10.000

## conclusion de la tabla de arriba:
Sumar el texto al B0 mejora el MRR de 0,091 a 0,114 (+0,024, alrededor de un 26 % más) con alpha = 0,5.  Con demasiado peso al texto (alpha = 2) se pierde casi toda.

## - experimentacion i

In [48]:
#leer licitaciones a mano

pd.set_option("display.max_colwidth", None)

def ver_licitacion(i, alpha=0.5, n_top=5):
    q = val.iloc[i]
    print("=" * 90)
    print("ID:", q["id"], "| fecha:", q["t"], "| psc:", q["psc"], "| naics:", q["naics"], "| office:", q["office"])
    print("TÍTULO:", q["title"])
    print("DESCRIPCIÓN:", txt(q["description"])[:1500])

    ids, p, sim, v = scores[q["id"]]
    tabla = pd.DataFrame({"parent_uei": ids, "p_b0": p, "sim_texto": sim,
                          "score": norm(p) + alpha * norm(sim)})
    tabla["puesto"] = tabla["score"].rank(ascending=False, method="first").astype(int)
    perfil = emp[emp.semestre == semestre_de(q["t"])][["parent_uei", "name", "n_awards", "texto_awards"]]
    tabla = tabla.merge(perfil, on="parent_uei", how="left")

    ganadores = set(gan.loc[gan.id == q["id"], "parent_uei"])
    g = tabla[tabla.parent_uei.isin(ganadores)].sort_values("puesto")
    print("\nGANADORES REALES y en qué puesto los puso nuestro ranking:")
    for _, f in g.iterrows():
        print(f"  puesto {f['puesto']:>5} | {f['name']} | n_awards={f['n_awards']} | sim={f['sim_texto']:.3f}")
        print("      ", txt(f["texto_awards"])[:300])

    print(f"\nTOP {n_top} DE NUESTRO RANKING:")
    for _, f in tabla.sort_values("puesto").head(n_top).iterrows():
        print(f"  puesto {f['puesto']:>5} | {f['name']} | sim={f['sim_texto']:.3f}")
        print("      ", txt(f["texto_awards"])[:300])

ver_licitacion(23)     # cambiar el número para ver otras

==========================================================================================
ID: W912HZ24B0001 | fecha: 2024-03-15 00:00:00 | psc: AH55 | naics: 541715 | office: W912HZ
TÍTULO: PRE-SOLICITATION - Coastal Research Amphibious Buggy (CRAB) Prototype Final Design and Build
DESCRIPCIÓN: SOLICITATION NO. W912HZ24B0001 PROCUREMENT TYPE: Pre-solicitation TITLE: Coastal Research Amphibious Buggy (CRAB) Prototype Final Design and Build CLASSIFICATION CODE: A   Research and Development NAICS CODE: 541715 - Research and Development in the Physical, Engineering, and Life Sciences (except Nanotechnology and Biotechnology) PSC CODE: AH55 - NATURAL RESOURCES & ENVIRONMENT R&D SVCS; OTHER NATURAL RESOURCES; R&D FACILITIES & MAJ EQUIPMENT DESCRIPTION: On or about 29 March 2024, this office will issue a 2-Step Invitation for Bid (IFB) for the design and fabrication of a Coastal Research Amphibious Buggy (CRAB) to be delivered to Duck, North Carolina. The solicitation will close on or about 30 April 2024. This solicitation is UNRESTRICTED AND OPEN TO BOTH LARGE AND SMALL BUSINESS PARTICIPATION. All contractors must be registered and have an active and verified account in the System for Award Management (SAM) in order to receive a contract award from any DoD activity. Contractors may access the Internet site at: https://www.sam.gov/ to register and/or obtain information about the SAM program. Contractors must ensure that the applicable NAICS code 541715 is included in their profile prior to submission of offer. SYSTEM FOR AWARD MANAGEMENT (SAM) REGISTRATION: Please be advised of on-line registration requirements for Contractor Registration and for Representations and Certifications Application which are now located in System for Award Management  SAM  database at https://sa

GANADORES REALES y en qué puesto los puso nuestro ranking:
  puesto  4357 | GIBBS & COX, INC. | n_awards=1 | sim=0.018
       PAC MINIMUM GUARANTEE

TOP 5 DE NUESTRO RANKING:
  puesto     1 | UNIVERSITY OF DELAWARE | sim=0.069
       ADVANCED IMAGING FOR ROADBED CONDITION MONITORING AND ASSESSMENT, FRA BAA 2021. USE ADVANCED TECHNOLOGIES LIKE DIGITAL IMAGE MEASUREMENTS FOR RAPID DEPLOYMENT TO ASSESS ROADBEDS AND OVERALL RAIL BRIDGE DISPLACEMENTS. | UNIVERSITY OF DELAWARE SERDP PROJECT 22-3175 | SERDP PROJECT MR20-1478 | SERDP ER
  puesto     2 | THE REGENTS OF THE UNIVERSITY OF CALIFORNIA, SAN DIEGO | sim=0.046
       MICE ANIMAL HUSBANDRY | GRADUATE STUDENT 1 TO PROVIDE TECHNICAL AND/OR ANALYTICAL SUPPORT. | ESTCP PROJECT CR23-7797 "RECOMMENDATIONS FOR UPDATES AND EXPANSIONS TO THE DEPARTMENT OF DEFENSE REGIONAL SEA LEVEL (DRSL) DATABASE" | UNIVERSITY OF CALIFORNIA RIVERSIDE-EVENT SPONSORSHIP. UC RIVERSIDE AND T
  puesto     3 | OREGON HEALTH & SCIENCE UNIVERSITY | sim=0.029
       EPC VI - SYSTEMATIC REVIEW OF MINDFULNESS-BASED INTERVENTIONS FOR MENTAL HEALTH IN CHILDREN AND ADOLESCENTS | FE-MRI AIRC SERVICES | PERSON-CENTERED CARE PLANNING FOR PERSONS WITH MULTIPLE CHRONIC CONDITIONS (MCC) | EDITING WEB HOSTING SERVICES. | SERDP PROJECT ER22-3286 | OHSU OCTRI MIRB 4337 | RES
  puesto     4 | DUCKS UNLIMITED INC | sim=0.000
       7.1 WETLAND MITIGATION BANK CREDITS
  puesto     5 | BATTELLE MEMORIAL INSTITUTE | sim=0.064
       BOX SHREDDER | BASE PERIOD (CARCOSA PHASE I) | RESEARCH AND DEVELOPMENT | EXPOSURE SIGNATURE DISCOVERY ALGORITHM FOR EPIGENETIC CHARACTERIZATION AND OBSERVATION | DARPA TRIAGE CHALLENGE (DTC) FOR THE SIGNATURES OF TRAUMA FOR ALGORITHM-ASSISTED CLINICAL ASSESSMENT, TRIAGE, AND OBSERVATION (STACATO) P

In [14]:
#14#
# definir selección (2023) y prueba (2024S1)
sel = lic[(lic.t >= "2023-01-01") & (lic.t < "2024-01-01")].copy()   # para elegir
pru = lic[lic.t >= "2024-01-01"].copy()                               # para medir una sola vez

for nombre, d in [("selección", sel), ("prueba", pru)]:
    print(f"{nombre:10s} | licitaciones: {len(d):3d} | ganadoras: {gan.id.isin(d.id).sum():3d}"
          f" | semestres: {sorted(d.t.map(semestre_de).unique())}")

 #----
 #Qué hace: separa selección (todo 2023) de prueba (2024S1) y muestra cuántas licitaciones hay en cada una.
 #Criterio: orden cronológico. Se elige con el pasado (2023) y se mide con el futuro (2024).

selección  | licitaciones: 130 | ganadoras: 217 | semestres: ['2023S1', '2023S2']
prueba     | licitaciones:  57 | ganadoras:  87 | semestres: ['2024S1']

In [15]:
#15#
# funciones para puntuar, rankear y medir cualquier conjunto de licitaciones
import evaluar as ev

def inicio_semestre(s):
    """'2023S2' -> '2023-07-01'"""
    anio, n = s.split("S")
    return f"{anio}-{'01' if n == '1' else '07'}-01"

def nuevo_tfidf(tokenizer=None):
    """Sin tokenizer: el TF-IDF base. Con tokenizer: ese tokenizador corta, normaliza y saca palabras vacías."""
    if tokenizer is None:
        return TfidfVectorizer(lowercase=True, stop_words="english", ngram_range=(1, 2),
                               min_df=2, max_features=100_000, sublinear_tf=True)
    return TfidfVectorizer(tokenizer=tokenizer, token_pattern=None, lowercase=False,
                           ngram_range=(1, 2), min_df=2, max_features=100_000, sublinear_tf=True)

def puntuar(lics, tokenizer=None):
    """Para cada licitación: (ids de candidatas, p del B0, coseno, vector de la licitación).
    El vocabulario de cada semestre se aprende solo con contratos anteriores a ese semestre."""
    sc = {}
    for s in sorted(lics["t"].map(semestre_de).unique()):
        corte = inicio_semestre(s)
        textos = hist.loc[pd.to_datetime(hist.fecha) < corte, "descripcion"].fillna("")
        tf = nuevo_tfidf(tokenizer).fit(textos)
        cand = emp[emp.semestre == s].reset_index(drop=True)
        M = tf.transform(cand["texto_awards"].fillna(""))
        ids = cand["parent_uei"].to_numpy()
        de_s = lics[lics["t"].map(semestre_de) == s]
        for _, q in de_s.iterrows():
            p = prior.p_b0(q, cand).reindex(cand["parent_uei"]).fillna(0).to_numpy()
            v = tf.transform([txt(q["title"]) + " " + txt(q["description"])])
            sc[q["id"]] = (ids, p, (M @ v.T).toarray().ravel(), v)
        print(f"{s} | vocabulario con contratos antes de {corte} | licitaciones: {len(de_s)} | candidatas: {len(cand)}")
    return sc

def ranking_de(sc, alpha, top=100, seed=0):
    """Igual que armar_ranking, pero recibe los puntajes como argumento."""
    rng = np.random.default_rng(seed)
    filas = []
    for lid, (ids, p, sim, v) in sc.items():
        s = norm(p) + alpha * norm(sim) + 1e-9 * rng.random(len(p))
        for puesto, i in enumerate(np.argsort(-s)[:top], 1):
            filas.append((lid, ids[i], puesto))
    return pd.DataFrame(filas, columns=["id", "parent_uei", "puesto"])

rk_b0_todo = pd.read_csv(f"b0_{V}.csv")   # ranking del B0 (lo genera la celda 1)

def medir(sc, alpha, lics):
    """Arma el ranking y lo evalúa contra el B0 en esas mismas licitaciones."""
    rk = ranking_de(sc, alpha)
    res = ev.evaluar(rk, lic, emp, gan[gan.id.isin(lics.id)], rk_b0_todo[rk_b0_todo.id.isin(lics.id)])
    f = res[res.conjunto == "todas"].iloc[0]
    return {"alpha": alpha, "N": int(f["N"]), "MRR": f["MRR"], "Hit@5": f["Hit@5"], "Hit@1": f["Hit@1"],
            "Δ MRR vs B0": f["Δ MRR"], "IC95 del Δ": f["Δ MRR IC95"],
            "Hit@100": f["Hit@100"], "Recall@100": f["Recall@100"]}

#--------
#Qué hace: junta en funciones lo que hacían las celdas #9 a #13, para aplicarlo a cualquier conjunto de licitaciones.
#Criterio: cada semestre se trata igual, con un vocabulario aprendido solo de su pasado.
#puntuar(lics, tokenizer) permite cambiar cómo se cortan las palabras (celda #19) sin tocar nada más.

In [16]:
#16#
#calcula los puntajes de selección y de prueba.
#aprende tres vocabularios.

sc_sel = puntuar(sel)
sc_pru = puntuar(pru)

2023S1 | vocabulario con contratos antes de 2023-01-01 | licitaciones: 74 | candidatas: 12526
2023S2 | vocabulario con contratos antes de 2023-07-01 | licitaciones: 56 | candidatas: 13125
2024S1 | vocabulario con contratos antes de 2024-01-01 | licitaciones: 57 | candidatas: 13880

In [17]:
#17#

#Esto prueba una grilla de alpha solo en 2023 y elige el de mayor MRR.

ALPHAS = [0, 0.05, 0.1, 0.25, 0.5, 0.75, 1, 1.5, 2]
tabla_sel = pd.DataFrame([medir(sc_sel, a, sel) for a in ALPHAS])
with pd.option_context("display.float_format", "{:.3f}".format):
    display(tabla_sel)

alpha_elegido = float(tabla_sel.loc[tabla_sel["MRR"].idxmax(), "alpha"])
print("alpha elegido en selección:", alpha_elegido)

#----
#la regla de elección se fija antes de mirar la prueba (el mayor MRR en selección), así la elección no está influida por 2024.

,alpha,N,MRR,Hit@5,Hit@1,Δ MRR vs B0,IC95 del Δ,Hit@100,Recall@100
0,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
1,0.050,130,0.124,0.246,0.069,-0.001,"(-0.004, +0.002)",0.631,0.525
2,0.100,130,0.126,0.254,0.069,0.001,"(-0.004, +0.005)",0.623,0.527
3,0.250,130,0.127,0.262,0.069,0.002,"(-0.006, +0.010)",0.585,0.497
4,0.500,130,0.129,0.277,0.069,0.004,"(-0.009, +0.017)",0.569,0.477
5,0.750,130,0.133,0.300,0.077,0.008,"(-0.011, +0.030)",0.569,0.470
6,1.000,130,0.142,0.269,0.092,0.017,"(-0.010, +0.047)",0.562,0.458
7,1.500,130,0.137,0.223,0.085,0.012,"(-0.027, +0.054)",0.531,0.433
8,2.000,130,0.138,0.185,0.092,0.013,"(-0.028, +0.060)",0.515,0.423

alpha elegido en selección: 1.0

In [18]:
#18#
#⚠️ LEER ESTO: Esto aplica el alpha elegido a 2024S1.
               #Es el número que se reporta. La disciplina es no volver a esta celda a probar otros alpha,
               #porque eso sería volver a elegir mirando la prueba.

tabla_pru = pd.DataFrame([medir(sc_pru, alpha_elegido, pru)])
with pd.option_context("display.float_format", "{:.3f}".format):
    display(tabla_pru)

,alpha,N,MRR,Hit@5,Hit@1,Δ MRR vs B0,IC95 del Δ,Hit@100,Recall@100
0,1.000,57,0.112,0.228,0.070,0.021,"(-0.008, +0.056)",0.509,0.443

## Conclusiones de la experimentación (celdas #14 a #18)

**Qué se hizo.** Se separaron los datos en orden cronológico para no usar información del futuro:
- **Selección (2023, 130 licitaciones):** se prueban valores de alpha y se elige el de mayor MRR.
- **Prueba (2024S1, 57 licitaciones):** se mide una sola vez, con el alpha elegido. Es el número que se reporta.
- El vocabulario de TF-IDF de cada semestre se aprende solo con contratos anteriores a ese semestre.

**Resultado.**
- Alpha elegido en selección: **1** (MRR 0,143 contra 0,125 del B0).
- En prueba (2024S1), con alpha = 1: **MRR 0,112 contra 0,091 del B0**, mejora de **+0,021**,
  con un intervalo de confianza del 95% de **(−0,008; +0,056)**.

**Qué se observa.**
- La mejora es positiva, pero el intervalo incluye el 0: con la validación limpia **no se puede afirmar
  que el texto mejore al B0**; podría ser azar.
- En el experimento anterior parecía significativa porque alpha se elegía y se medía con las mismas licitaciones.
- En 2023 el texto ayuda menos que en 2024: con alpha = 0,5 mejora +0,006 en 2023 y +0,024 en 2024.
- En 2023, al subir alpha, baja el Hit@100 (de 0,638 con el B0 a 0,569 con alpha = 1 y 0,523 con alpha = 2):
  el texto saca de la lista a ganadoras que el B0 sí encontraba.
- La señal de texto, tal como está armada, es débil e inestable.

**Conclusión y próximos pasos.**
- Con TF-IDF simple, la mejora sobre el B0 es positiva pero **no significativa**.
- Ahora el marco de evaluación es confiable: toda variante nueva se elige en 2023 y se mide una vez en 2024S1.
- Próximos experimentos, con este mismo esquema: lematizar, reducir dimensiones con SVD, embeddings
  y comparar contra cada contrato por separado.
- Repetir lo mejor en una vertical grande (por ejemplo `j`, 4.504 licitaciones), donde los intervalos se achican

# - Experimentacion ii

In [19]:
#19# tokenizadores
# lematizar y recortar a la raíz
!pip -q install nltk
import re, nltk
from functools import lru_cache
from nltk.stem import SnowballStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
nltk.download("wordnet", quiet=True)

PALABRA = re.compile(r"(?u)\b\w\w+\b")      # la misma regla de corte que usa TfidfVectorizer
_lematizador = WordNetLemmatizer()
_recortador = SnowballStemmer("english")

@lru_cache(maxsize=None)
def lema(w):
    return _lematizador.lemmatize(w)

@lru_cache(maxsize=None)
def raiz(w):
    return _recortador.stem(w)

def tokens_lema(texto):
    return [lema(w) for w in PALABRA.findall(texto.lower()) if w not in ENGLISH_STOP_WORDS]

def tokens_raiz(texto):
    return [raiz(w) for w in PALABRA.findall(texto.lower()) if w not in ENGLISH_STOP_WORDS]

ej = "Laboratories providing research services and genetic analyses for studies"
print("original:", ej)
print("lemas:   ", tokens_lema(ej))
print("raíces:  ", tokens_raiz(ej))

#--------
#Qué hace: define dos formas de normalizar las palabras antes de armar los vectores.
#Criterio: misma regla de corte y mismas palabras vacías que el TF-IDF base; solo cambia la normalización.

original: Laboratories providing research services and genetic analyses for studies
lemas:    ['laboratory', 'providing', 'research', 'service', 'genetic', 'analysis', 'study']
raíces:   ['laboratori', 'provid', 'research', 'servic', 'genet', 'analys', 'studi']

In [20]:
#20# Puntuar la selección con cada variante
sc_sel_lema = puntuar(sel, tokens_lema)
sc_sel_raiz = puntuar(sel, tokens_raiz)

2023S1 | vocabulario con contratos antes de 2023-01-01 | licitaciones: 74 | candidatas: 12526
2023S2 | vocabulario con contratos antes de 2023-07-01 | licitaciones: 56 | candidatas: 13125
2023S1 | vocabulario con contratos antes de 2023-01-01 | licitaciones: 74 | candidatas: 12526
2023S2 | vocabulario con contratos antes de 2023-07-01 | licitaciones: 56 | candidatas: 13125

In [21]:
#21# Grilla de alpha para las tres variantes
variantes = {"TF-IDF base": sc_sel, "lematizado": sc_sel_lema, "raíz": sc_sel_raiz}
partes = []
for nombre, sc in variantes.items():
    t = pd.DataFrame([medir(sc, a, sel) for a in ALPHAS])
    t.insert(0, "variante", nombre)
    partes.append(t)
tabla_var = pd.concat(partes, ignore_index=True)
mejor_var = tabla_var.loc[tabla_var.groupby("variante", sort=False)["MRR"].idxmax()]

with pd.option_context("display.float_format", "{:.3f}".format):
    display(tabla_var)
    print("Mejor alpha de cada variante (en selección):")
    display(mejor_var[["variante", "alpha", "MRR", "Hit@5", "Hit@1", "Δ MRR vs B0", "IC95 del Δ"]])

    #Qué hace: mide las tres variantes con todos los alpha en selección, y muestra el mejor alpha de cada una.

,variante,alpha,N,MRR,Hit@5,Hit@1,Δ MRR vs B0,IC95 del Δ,Hit@100,Recall@100
0,TF-IDF base,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
1,TF-IDF base,0.050,130,0.124,0.246,0.069,-0.001,"(-0.004, +0.002)",0.631,0.525
2,TF-IDF base,0.100,130,0.126,0.254,0.069,0.001,"(-0.004, +0.005)",0.623,0.527
3,TF-IDF base,0.250,130,0.127,0.262,0.069,0.002,"(-0.006, +0.010)",0.585,0.497
4,TF-IDF base,0.500,130,0.129,0.277,0.069,0.004,"(-0.009, +0.017)",0.569,0.477
5,TF-IDF base,0.750,130,0.133,0.300,0.077,0.008,"(-0.011, +0.030)",0.569,0.470
6,TF-IDF base,1.000,130,0.142,0.269,0.092,0.017,"(-0.010, +0.047)",0.562,0.458
7,TF-IDF base,1.500,130,0.137,0.223,0.085,0.012,"(-0.027, +0.054)",0.531,0.433
8,TF-IDF base,2.000,130,0.138,0.185,0.092,0.013,"(-0.028, +0.060)",0.515,0.423
9,lematizado,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
10,lematizado,0.050,130,0.124,0.246,0.069,-0.001,"(-0.004, +0.002)",0.631,0.521
11,lematizado,0.100,130,0.126,0.254,0.069,0.001,"(-0.004, +0.006)",0.631,0.530
12,lematizado,0.250,130,0.128,0.262,0.069,0.003,"(-0.006, +0.012)",0.592,0.506
13,lematizado,0.500,130,0.130,0.269,0.069,0.005,"(-0.010, +0.019)",0.592,0.502
14,lematizado,0.750,130,0.133,0.269,0.077,0.008,"(-0.011, +0.030)",0.585,0.488
15,lematizado,1.000,130,0.144,0.269,0.092,0.019,"(-0.009, +0.048)",0.569,0.473
16,lematizado,1.500,130,0.137,0.238,0.085,0.012,"(-0.026, +0.053)",0.531,0.433
17,lematizado,2.000,130,0.140,0.192,0.100,0.015,"(-0.027, +0.063)",0.531,0.438
18,raíz,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
19,raíz,0.050,130,0.124,0.238,0.069,-0.001,"(-0.004, +0.002)",0.638,0.529
20,raíz,0.100,130,0.126,0.262,0.069,0.001,"(-0.004, +0.005)",0.631,0.532
21,raíz,0.250,130,0.127,0.254,0.069,0.002,"(-0.006, +0.010)",0.615,0.519
22,raíz,0.500,130,0.131,0.269,0.069,0.006,"(-0.008, +0.020)",0.623,0.535
23,raíz,0.750,130,0.133,0.269,0.077,0.008,"(-0.011, +0.030)",0.600,0.506
24,raíz,1.000,130,0.144,0.269,0.108,0.019,"(-0.008, +0.049)",0.577,0.485
25,raíz,1.500,130,0.130,0.223,0.069,0.005,"(-0.028, +0.041)",0.562,0.470
26,raíz,2.000,130,0.133,0.208,0.085,0.008,"(-0.030, +0.050)",0.554,0.461

Mejor alpha de cada variante (en selección):

       variante  alpha   MRR  Hit@5  Hit@1  Δ MRR vs B0        IC95 del Δ
6   TF-IDF base  1.000 0.142  0.269  0.092        0.017  (-0.010, +0.047)
15   lematizado  1.000 0.144  0.269  0.092        0.019  (-0.009, +0.048)
24         raíz  1.000 0.144  0.269  0.108        0.019  (-0.008, +0.049)

In [22]:
#22# Comparar contra el TF-IDF base y decidir

def comparar(sc_nueva, alpha_nueva, sc_ref, alpha_ref, lics):
    """Δ de MRR de una variante contra una referencia, licitación por licitación, con IC95 (bootstrap)."""
    g = gan[gan.id.isin(lics.id)]
    a = ev.por_licitacion(ranking_de(sc_nueva, alpha_nueva), g)["MRR"]
    b = ev.por_licitacion(ranking_de(sc_ref, alpha_ref), g)["MRR"]
    a, b = a.align(b, join="inner")
    lo, hi = ev.bootstrap_delta(a.values, b.values)
    return {"Δ MRR vs base": a.mean() - b.mean(), "IC95 bajo": lo, "IC95 alto": hi,
            "licitaciones que mejoran": int((a > b).sum()), "que empeoran": int((a < b).sum()),
            "iguales": int((a == b).sum())}

alpha_de = dict(zip(mejor_var["variante"], mejor_var["alpha"]))
comp = pd.DataFrame([{"variante": v, "alpha": alpha_de[v],
                      **comparar(variantes[v], alpha_de[v], variantes["TF-IDF base"], alpha_de["TF-IDF base"], sel)}
                     for v in ["lematizado", "raíz"]])
with pd.option_context("display.float_format", "{:.3f}".format):
    display(comp)

# Regla fijada antes de mirar: se adopta solo si el IC95 del Δ contra el base es todo positivo.
claras = comp[comp["IC95 bajo"] > 0]
if claras.empty:
    ganadora = "TF-IDF base"
    print("Ninguna variante mejora claramente al TF-IDF base (todos los IC95 incluyen el 0). Se mantiene TF-IDF base.")
else:
    ganadora = claras.sort_values("Δ MRR vs base", ascending=False).iloc[0]["variante"]
    print("Se adopta:", ganadora, "con alpha", alpha_de[ganadora])

 #---
 #Qué hace: compara cada variante, con su mejor alpha, contra el TF-IDF base, licitación por licitación.
           # Muestra cuánto cambia el MRR, el intervalo de esa diferencia y cuántas licitaciones mejoran, empeoran o quedan igual. Después aplica la regla.

#Criterio: la pregunta ya no es “¿mejora al B0?” sino “¿mejora al TF-IDF que ya tenemos?”. ((Por eso la comparación es contra el base)).

,variante,alpha,Δ MRR vs base,IC95 bajo,IC95 alto,licitaciones que mejoran,que empeoran,iguales
0,lematizado,1.000,0.001,-0.002,0.006,25,20,85
1,raíz,1.000,0.002,-0.004,0.008,34,23,73

Ninguna variante mejora claramente al TF-IDF base (todos los IC95 incluyen el 0). Se mantiene TF-IDF base.

In [23]:
#23# Prueba, solo si se adoptó una variante

if ganadora == "TF-IDF base":
    print("No se adopta ninguna variante, así que no se mide nada nuevo en prueba.")
    print("El resultado reportado sigue siendo el de la experimentación i (celdas #14 a #18):")
    print("TF-IDF base con alpha = 1 → MRR 0,112 contra 0,091 del B0 en 2024S1.")
else:
    tok = {"lematizado": tokens_lema, "raíz": tokens_raiz}[ganadora]
    sc_pru_v = puntuar(pru, tok)
    with pd.option_context("display.float_format", "{:.3f}".format):
        display(pd.DataFrame([medir(sc_pru_v, alpha_de[ganadora], pru)]))

#----
#Qué hace: si la #22 adoptó una variante, la mide una vez en 2024S1. Si no, no mide nada, porque no hay nada nuevo que reportar.

No se adopta ninguna variante, así que no se mide nada nuevo en prueba.
El resultado reportado sigue siendo el de la experimentación i (celdas #14 a #18):
TF-IDF base con alpha = 1 → MRR 0,112 contra 0,091 del B0 en 2024S1.

## Conclusiones de la experimentación ii (celdas #19 a #23): lematizar y recortar a la raíz

**Qué se probó.** TF-IDF compara palabras exactas: "service" y "services" cuentan como términos distintos.
Se probaron dos formas de normalizar las palabras antes de armar los vectores:
- **Lematizar** (WordNet): lleva cada palabra a su forma de diccionario ("laboratories" → "laboratory").
- **Recortar a la raíz** (Snowball): le corta las terminaciones con reglas fijas ("laboratories" → "laboratori").

Todo lo demás quedó igual que en la experimentación i: B0, mezcla con alpha, selección 2023 y prueba 2024S1.

**Regla de decisión (fijada antes de mirar los resultados).** Cada variante usa su mejor alpha en selección y se
compara contra el TF-IDF base licitación por licitación. Se adopta solo si el IC95 de la diferencia es todo positivo.

**Resultado en selección (2023, 130 licitaciones).**

| Variante | Mejor alpha | MRR | Δ vs TF-IDF base | IC95 del Δ | Mejoran / empeoran / iguales |
|---|---|---|---|---|---|
| TF-IDF base | 1 | 0,143 | — | — | — |
| Lematizado | 1 | 0,144 | +0,001 | (−0,002; +0,006) | 27 / 21 / 82 |
| Raíz | 1 | 0,140 | −0,002 | (−0,014; +0,007) | 35 / 23 / 72 |

**Qué se observa.**
- Lematizar da prácticamente lo mismo que el base: las mejoras y los empeoramientos se cancelan.
- Recortar a la raíz mejora más licitaciones de las que empeora (35 contra 23), pero el MRR promedio baja:
  mejora un poco a muchas ganadoras que estaban abajo y arruina a unas pocas que estaban arriba.
  El MRR castiga mucho perder los primeros puestos (del 1 al 2 se pierde 0,5; del 50 al 20 se gana 0,03).
- Ningún IC95 es todo positivo.

**Decisión.** Se mantiene el TF-IDF base (más simple y más fácil de explicar). No se mide nada nuevo en prueba:
el resultado reportado sigue siendo el de la experimentación i (MRR 0,112 contra 0,091 del B0 en 2024S1).

**Conclusión.** Las diferencias de forma de las palabras no son el problema principal del texto.
La hipótesis siguiente es que el problema es de significado (sinónimos y temas), que es lo que atacan
SVD (experimentación iii) y los embeddings.

## experimentación iii: SVD

In [24]:
#24# funciones de SVD
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import normalize

def puntuar_svd(lics, k):
    """Como puntuar, pero compara licitación y empresa en un espacio de k 'temas' (SVD sobre TF-IDF)."""
    sc = {}
    for s in sorted(lics["t"].map(semestre_de).unique()):
        corte = inicio_semestre(s)
        textos = hist.loc[pd.to_datetime(hist.fecha) < corte, "descripcion"].fillna("")
        tf = nuevo_tfidf()
        X = tf.fit_transform(textos)                                   # TF-IDF de los contratos del pasado
        svd = TruncatedSVD(n_components=k, random_state=0).fit(X)      # aprende k temas
        cand = emp[emp.semestre == s].reset_index(drop=True)
        M = normalize(svd.transform(tf.transform(cand["texto_awards"].fillna(""))))   # empresas en temas
        ids = cand["parent_uei"].to_numpy()
        de_s = lics[lics["t"].map(semestre_de) == s]
        for _, q in de_s.iterrows():
            p = prior.p_b0(q, cand).reindex(cand["parent_uei"]).fillna(0).to_numpy()
            v = tf.transform([txt(q["title"]) + " " + txt(q["description"])])
            u = normalize(svd.transform(v))                            # licitación en temas
            sim = np.clip(M @ u.ravel(), 0, None)                      # coseno; los negativos pasan a 0
            sc[q["id"]] = (ids, p, sim, v)
        print(f"{s} | k={k} | información que conservan los temas: {svd.explained_variance_ratio_.sum():.0%}"
              f" | licitaciones: {len(de_s)} | candidatas: {len(cand)}")
    return sc

def mezclar(sc_a, sc_b, w):
    """Similitud = la de sc_a + w × la de sc_b (cada una escalada a 0-1)."""
    return {l: (sc_a[l][0], sc_a[l][1], norm(sc_a[l][2]) + w * norm(sc_b[l][2]), sc_a[l][3]) for l in sc_a}

#--------
#Qué hace: representa los textos por "temas" (combinaciones de palabras que suelen aparecer juntas) en vez de por palabras exactas.
#Criterio: atacar el problema de significado (sinónimos). Los temas se aprenden solo con el pasado de cada semestre.

In [26]:
#25# Puntuar la selección con las variantes

#25#
sc_sel_svd100 = puntuar_svd(sel, 100)
sc_sel_svd300 = puntuar_svd(sel, 300)
sc_sel_mix = mezclar(sc_sel, sc_sel_svd100, 0.5)     # TF-IDF + SVD 100, peso fijado de antemano

2023S1 | k=100 | información que conservan los temas: 22% | licitaciones: 74 | candidatas: 12526
2023S2 | k=100 | información que conservan los temas: 21% | licitaciones: 56 | candidatas: 13125
2023S1 | k=300 | información que conservan los temas: 29% | licitaciones: 74 | candidatas: 12526
2023S2 | k=300 | información que conservan los temas: 29% | licitaciones: 56 | candidatas: 13125

In [27]:
#26# Grilla de alpha, comparación y decisión

variantes_svd = {"TF-IDF base": sc_sel, "SVD 100": sc_sel_svd100, "SVD 300": sc_sel_svd300,
                 "TF-IDF + SVD 100": sc_sel_mix}
partes = []
for nombre, sc in variantes_svd.items():
    t = pd.DataFrame([medir(sc, a, sel) for a in ALPHAS])
    t.insert(0, "variante", nombre)
    partes.append(t)
tabla_svd = pd.concat(partes, ignore_index=True)
mejor_svd = tabla_svd.loc[tabla_svd.groupby("variante", sort=False)["MRR"].idxmax()]
alpha_svd = dict(zip(mejor_svd["variante"], mejor_svd["alpha"]))
comp_svd = pd.DataFrame([{"variante": v, "alpha": alpha_svd[v],
                          **comparar(variantes_svd[v], alpha_svd[v], sc_sel, alpha_svd["TF-IDF base"], sel)}
                         for v in ["SVD 100", "SVD 300", "TF-IDF + SVD 100"]])

with pd.option_context("display.float_format", "{:.3f}".format):
    display(tabla_svd)
    print("Mejor alpha de cada variante (en selección):")
    display(mejor_svd[["variante", "alpha", "MRR", "Hit@5", "Hit@1", "Δ MRR vs B0", "IC95 del Δ"]])
    print("Comparación contra el TF-IDF base:")
    display(comp_svd)

# Regla fijada antes de mirar: se adopta solo si el IC95 del Δ contra el base es todo positivo.
claras = comp_svd[comp_svd["IC95 bajo"] > 0]
if claras.empty:
    ganadora_svd = "TF-IDF base"
    print("Ninguna variante mejora claramente al TF-IDF base. Se mantiene TF-IDF base.")
else:
    ganadora_svd = claras.sort_values("Δ MRR vs base", ascending=False).iloc[0]["variante"]
    print("Se adopta:", ganadora_svd, "con alpha", alpha_svd[ganadora_svd])

 #----
 #Qué hace: lo mismo que la #21 y la #22 juntas, para las variantes de SVD. Usa la función comparar de la #22.

,variante,alpha,N,MRR,Hit@5,Hit@1,Δ MRR vs B0,IC95 del Δ,Hit@100,Recall@100
0,TF-IDF base,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
1,TF-IDF base,0.050,130,0.124,0.246,0.069,-0.001,"(-0.004, +0.002)",0.631,0.525
2,TF-IDF base,0.100,130,0.126,0.254,0.069,0.001,"(-0.004, +0.005)",0.623,0.527
3,TF-IDF base,0.250,130,0.127,0.262,0.069,0.002,"(-0.006, +0.010)",0.585,0.497
4,TF-IDF base,0.500,130,0.129,0.277,0.069,0.004,"(-0.009, +0.017)",0.569,0.477
5,TF-IDF base,0.750,130,0.133,0.300,0.077,0.008,"(-0.011, +0.030)",0.569,0.470
6,TF-IDF base,1.000,130,0.142,0.269,0.092,0.017,"(-0.010, +0.047)",0.562,0.458
7,TF-IDF base,1.500,130,0.137,0.223,0.085,0.012,"(-0.027, +0.054)",0.531,0.433
8,TF-IDF base,2.000,130,0.138,0.185,0.092,0.013,"(-0.028, +0.060)",0.515,0.423
9,SVD 100,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
10,SVD 100,0.050,130,0.123,0.238,0.069,-0.002,"(-0.006, +0.001)",0.600,0.495
11,SVD 100,0.100,130,0.124,0.246,0.069,-0.001,"(-0.005, +0.003)",0.592,0.487
12,SVD 100,0.250,130,0.121,0.238,0.069,-0.004,"(-0.009, +0.001)",0.554,0.449
13,SVD 100,0.500,130,0.116,0.246,0.069,-0.009,"(-0.019, -0.001)",0.523,0.413
14,SVD 100,0.750,130,0.112,0.231,0.069,-0.013,"(-0.026, -0.003)",0.492,0.376
15,SVD 100,1.000,130,0.108,0.223,0.069,-0.017,"(-0.031, -0.005)",0.469,0.352
16,SVD 100,1.500,130,0.061,0.192,0.023,-0.064,"(-0.099, -0.034)",0.454,0.334
17,SVD 100,2.000,130,0.046,0.123,0.008,-0.079,"(-0.120, -0.044)",0.423,0.311
18,SVD 300,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
19,SVD 300,0.050,130,0.124,0.238,0.069,-0.001,"(-0.005, +0.002)",0.623,0.509
20,SVD 300,0.100,130,0.124,0.254,0.069,-0.001,"(-0.005, +0.003)",0.608,0.507
21,SVD 300,0.250,130,0.122,0.246,0.069,-0.003,"(-0.009, +0.003)",0.562,0.455
22,SVD 300,0.500,130,0.119,0.231,0.069,-0.006,"(-0.017, +0.002)",0.562,0.454
23,SVD 300,0.750,130,0.115,0.223,0.069,-0.010,"(-0.024, +0.003)",0.538,0.427
24,SVD 300,1.000,130,0.114,0.223,0.077,-0.011,"(-0.027, +0.003)",0.515,0.405
25,SVD 300,1.500,130,0.069,0.169,0.015,-0.056,"(-0.088, -0.027)",0.508,0.394
26,SVD 300,2.000,130,0.046,0.077,0.015,-0.079,"(-0.124, -0.039)",0.492,0.376
27,TF-IDF + SVD 100,0.000,130,0.125,0.246,0.069,0.000,"(+0.000, +0.000)",0.638,0.535
28,TF-IDF + SVD 100,0.050,130,0.124,0.246,0.069,-0.001,"(-0.004, +0.002)",0.638,0.531
29,TF-IDF + SVD 100,0.100,130,0.126,0.262,0.069,0.001,"(-0.003, +0.006)",0.623,0.527
30,TF-IDF + SVD 100,0.250,130,0.127,0.246,0.069,0.002,"(-0.005, +0.009)",0.608,0.505
31,TF-IDF + SVD 100,0.500,130,0.128,0.262,0.069,0.003,"(-0.010, +0.015)",0.608,0.498
32,TF-IDF + SVD 100,0.750,130,0.131,0.262,0.077,0.006,"(-0.012, +0.027)",0.562,0.458
33,TF-IDF + SVD 100,1.000,130,0.137,0.269,0.092,0.012,"(-0.010, +0.037)",0.569,0.463
34,TF-IDF + SVD 100,1.500,130,0.141,0.231,0.092,0.016,"(-0.019, +0.053)",0.562,0.446
35,TF-IDF + SVD 100,2.000,130,0.127,0.215,0.069,0.002,"(-0.033, +0.039)",0.554,0.440

Mejor alpha de cada variante (en selección):

            variante  alpha   MRR  Hit@5  Hit@1  Δ MRR vs B0        IC95 del Δ
6        TF-IDF base  1.000 0.142  0.269  0.092        0.017  (-0.010, +0.047)
9            SVD 100  0.000 0.125  0.246  0.069        0.000  (+0.000, +0.000)
18           SVD 300  0.000 0.125  0.246  0.069        0.000  (+0.000, +0.000)
34  TF-IDF + SVD 100  1.500 0.141  0.231  0.092        0.016  (-0.019, +0.053)

Comparación contra el TF-IDF base:

,variante,alpha,Δ MRR vs base,IC95 bajo,IC95 alto,licitaciones que mejoran,que empeoran,iguales
0,SVD 100,0.000,-0.017,-0.047,0.010,50,34,46
1,SVD 300,0.000,-0.017,-0.047,0.010,50,34,46
2,TF-IDF + SVD 100,1.500,-0.001,-0.015,0.013,27,34,69

Ninguna variante mejora claramente al TF-IDF base. Se mantiene TF-IDF base.

In [28]:
#27# Prueba, solo si se adoptó una variante

if ganadora_svd == "TF-IDF base":
    print("No se adopta ninguna variante, así que no se mide nada nuevo en prueba.")
    print("El resultado reportado sigue siendo el de la experimentación i (celdas #14 a #18):")
    print("TF-IDF base con alpha = 1 → MRR 0,112 contra 0,091 del B0 en 2024S1.")
else:
    armar = {"SVD 100": lambda: puntuar_svd(pru, 100),
             "SVD 300": lambda: puntuar_svd(pru, 300),
             "TF-IDF + SVD 100": lambda: mezclar(sc_pru, puntuar_svd(pru, 100), 0.5)}[ganadora_svd]
    with pd.option_context("display.float_format", "{:.3f}".format):
        display(pd.DataFrame([medir(armar(), alpha_svd[ganadora_svd], pru)]))

No se adopta ninguna variante, así que no se mide nada nuevo en prueba.
El resultado reportado sigue siendo el de la experimentación i (celdas #14 a #18):
TF-IDF base con alpha = 1 → MRR 0,112 contra 0,091 del B0 en 2024S1.

## Conclusiones de la experimentación iii (celdas #24 a #27): SVD (temas)

**Qué se probó.** SVD (también llamado LSA) aprende, con los contratos del pasado, "temas": combinaciones de palabras
que suelen aparecer juntas. Cada texto pasa a describirse por cuánto tiene de cada tema, en lugar de por palabras exactas.
Así dos textos pueden parecerse sin compartir palabras. Se probaron tres variantes:
- **SVD 100** y **SVD 300**: el texto representado con 100 o 300 temas, en lugar del TF-IDF.
- **TF-IDF + SVD 100**: la similitud del TF-IDF más la mitad de la de SVD (peso fijado de antemano).

Misma regla de decisión que en la experimentación ii: se adopta solo si el IC95 del Δ contra el TF-IDF base es todo positivo.

**Resultado en selección (2023, 130 licitaciones).**

| Variante | Mejor alpha | MRR | Δ vs TF-IDF base | IC95 del Δ | Mejoran / empeoran / iguales |
|---|---|---|---|---|---|
| TF-IDF base | 1 | 0,143 | — | — | — |
| SVD 100 | 0 (no usarla) | 0,125 | −0,018 | (−0,048; +0,010) | 50 / 35 / 45 |
| SVD 300 | 0 (no usarla) | 0,125 | −0,018 | (−0,048; +0,010) | 50 / 35 / 45 |
| TF-IDF + SVD 100 | 1,5 | 0,141 | −0,002 | (−0,015; +0,013) | 26 / 35 / 69 |

**Qué se observa.**
- SVD sola empeora al B0, y de forma significativa: con SVD 100 y alpha ≥ 0,5, el IC95 del Δ contra el B0 es todo negativo
  (con alpha = 1: MRR 0,108, IC95 de −0,031 a −0,005). Por eso su mejor alpha es 0.
- Con 300 temas empeora menos que con 100: cuantos más temas, más se parece a las palabras originales.
- Sumada al TF-IDF no agrega nada (−0,002) y empeora más licitaciones de las que mejora.
- Como el mejor alpha de SVD sola es 0, esa comparación es en realidad B0 contra TF-IDF base: el TF-IDF empeora 50
  licitaciones y mejora 35, pero sus mejoras pesan más (sube ganadoras a los primeros puestos).

**Decisión.** Se mantiene el TF-IDF base. No se mide nada nuevo en prueba: el resultado reportado sigue siendo el de la
experimentación i (MRR 0,112 contra 0,091 del B0 en 2024S1).

**Conclusión.** Los temas son demasiado generales para distinguir entre ~13.000 empresas que en su mayoría hacen
investigación y desarrollo: al comprimir se pierden las palabras raras (como "ninds"), que son las que identifican a la
empresa correcta. Junto con la experimentación ii: lo que sirve del texto son las coincidencias de palabras específicas;
normalizarlas no ayuda y agruparlas en temas hace daño. Los embeddings son la última prueba de la hipótesis de
"problema de significado".

## - Experimentación v

In [29]:
#28# chequeo de GPU y variables

import torch
print("¿GPU disponible?:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Modelo de GPU:", torch.cuda.get_device_name(0))
!pip install -q sentence-transformers

nombres = ["hist","emp","lic","gan","prior","sel","pru","sc_sel","sc_pru",
           "alpha_elegido","ranking_de","comparar","mezclar","semestre_de",
           "inicio_semestre","txt","ev","ALPHAS"]
faltan = [n for n in nombres if n not in globals()]
print("Faltan:", faltan if faltan else "nada, está todo")
print("Columnas de hist:", list(hist.columns))

## esto confirma que Colabnos dio GPU, instala sentence-transformers y verifica que existan todas las variables que necesitamos de las celdas anteriores.

¿GPU disponible?: True
Modelo de GPU: Tesla T4
Faltan: nada, está todo
Columnas de hist: ['fecha', 'parent_uei', 'psc', 'naics', 'office', 'set_aside', 'descripcion']

In [31]:
#29#
#cargar el modelo y estimar el tiempo
from sentence_transformers import SentenceTransformer
import numpy as np, time

modelo = SentenceTransformer("all-MiniLM-L6-v2", device="cuda")
modelo.max_seq_length = 256
modelo.half()

def codificar(textos, lote=128):
    return modelo.encode(list(textos), batch_size=lote, normalize_embeddings=True,
                         show_progress_bar=True, convert_to_numpy=True).astype("float32")

t0 = time.time()
prueba = codificar(hist["descripcion"].fillna("").head(2000))
seg = time.time() - t0
print("forma:", prueba.shape, "| tiempo:", round(seg, 1), "s")
print("estimado para todo hist:", round(seg * len(hist) / 2000 / 60, 1), "min")

#----
#Qué hace: carga all-MiniLM-L6-v2, que convierte cada texto en 384 números, y lo prueba con 2.000 contratos
#          para estimar cuánto tardará con todos.
#Criterio:es un modelo chico y rápido.
#           max_seq_length=256 es el tope de palabras que lee, y lo que pasa de ahí se ignora.
#.          half() usa media precisión, que es más rápida y no cambia el ranking.
#           normalize_embeddings=True deja cada vector con largo 1, igual que el TF-IDF, así que producto punto = coseno.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

forma: (2000, 384) | tiempo: 2.4 s
estimado para todo hist: 1.7 min

In [32]:
#30#
# vectores de todos los contratos y de las licitaciones
t0 = time.time()
emb_hist = codificar(hist["descripcion"].fillna(""))
np.save("/content/emb_hist.npy", emb_hist)
print("contratos:", emb_hist.shape, "|", round((time.time() - t0) / 60, 1), "min")

textos_lic = lic["title"].map(txt) + " " + lic["description"].map(txt)
emb_lic = codificar(textos_lic)
fila_lic = dict(zip(lic["id"], range(len(lic))))
print("licitaciones:", emb_lic.shape)

#---
#Qué hace: convierte cada contrato del historial y cada licitación en un vector.

Batches:   0%|          | 0/663 [00:00<?, ?it/s]

contratos: (84835, 384) | 0.6 min

Batches:   0%|          | 0/3 [00:00<?, ?it/s]

licitaciones: (328, 384)

In [33]:
#31#
# Experimentación v: perfiles y puntajes con embeddings
from scipy.sparse import csr_matrix

def puntuar_emb(lics):
    sc = {}
    fechas = pd.to_datetime(hist["fecha"])
    for s in sorted(lics["t"].map(semestre_de).unique()):
        corte = inicio_semestre(s)
        m = ((fechas < corte) & hist["parent_uei"].notna()).to_numpy()
        codigos, unicos = pd.factorize(hist.loc[m, "parent_uei"].to_numpy())
        n = len(codigos)
        suma = csr_matrix((np.ones(n, dtype="float32"), (codigos, np.arange(n))),
                          shape=(len(unicos), n)) @ emb_hist[m]
        norma = np.linalg.norm(suma, axis=1, keepdims=True)
        norma[norma == 0] = 1
        perfil = suma / norma

        cand = emp[emp.semestre == s].reset_index(drop=True)
        ids = cand["parent_uei"].to_numpy()
        pos = pd.Series(np.arange(len(unicos)), index=unicos).reindex(ids)
        tiene = pos.notna().to_numpy()
        P = np.zeros((len(ids), perfil.shape[1]), dtype="float32")
        P[tiene] = perfil[pos[tiene].astype(int).to_numpy()]

        de_s = lics[lics["t"].map(semestre_de) == s]
        for _, q in de_s.iterrows():
            p = prior.p_b0(q, cand).reindex(cand["parent_uei"]).fillna(0).to_numpy()
            v = emb_lic[fila_lic[q["id"]]]
            sim = np.clip(P @ v, 0, None)
            sc[q["id"]] = (ids, p, sim, v)
    return sc

#---
#Qué hace: para cada semestre, promedia los vectores de los contratos de cada empresa anteriores al corte,
#          deja el promedio con largo 1 y calcula el coseno con la licitación.
#Criterio: Promediar vectores da el “centro” de lo que hace la empresa.
#          Las empresas sin historial quedan con similitud 0, igual que en TF-IDF.
#          Los cosenos negativos se recortan a 0, igual que en SVD.

In [34]:
#32#
#tabla en selección (2023)

def mrr_de(sc, a, lics):
    g = gan[gan.id.isin(lics.id)]
    return ev.por_licitacion(ranking_de(sc, a), g)["MRR"].mean()

sc_sel_emb = puntuar_emb(sel)
sc_sel_mixemb = mezclar(sc_sel, sc_sel_emb, 0.5)

filas = []
for a in ALPHAS:
    filas.append({"alpha": a,
                  "B0+TF-IDF (base)": mrr_de(sc_sel, a, sel),
                  "B0+embeddings": mrr_de(sc_sel_emb, a, sel),
                  "B0+mezcla TF-IDF y emb": mrr_de(sc_sel_mixemb, a, sel)})
tabla_emb = pd.DataFrame(filas).set_index("alpha").round(3)
display(tabla_emb)

#--
#Qué hace: compara por MRR, para cada alpha, tres versiones: B0+TF-IDF (la base),
#          B0+embeddings y B0+mezcla mitad TF-IDF y mitad embeddings.
#Criterio: la mezcla prueba si el TF-IDF (palabras exactas) y los embeddings (significado) se complementan.

       B0+TF-IDF (base)  B0+embeddings  B0+mezcla TF-IDF y emb
alpha
0.00              0.125          0.125                   0.125
0.05              0.124          0.128                   0.126
0.10              0.126          0.130                   0.129
0.25              0.127          0.133                   0.133
0.50              0.129          0.134                   0.135
0.75              0.133          0.135                   0.143
1.00              0.142          0.138                   0.145
1.50              0.137          0.137                   0.159
2.00              0.138          0.136                   0.153

In [35]:
#33#
opciones = {"B0+embeddings": sc_sel_emb, "B0+mezcla TF-IDF y emb": sc_sel_mixemb}
nombre, alpha_emb = max(((c, a) for c in opciones for a in ALPHAS),
                        key=lambda x: tabla_emb.loc[x[1], x[0]])
print("Mejor en selección:", nombre, "| alpha =", alpha_emb)

res = comparar(opciones[nombre], alpha_emb, sc_sel, alpha_elegido, sel)
display(pd.Series(res).round(3))

ganadora_emb = res["IC95 bajo"] > 0
print("Se adopta en prueba." if ganadora_emb else
      "No supera a B0+TF-IDF con la regla fijada: se mantiene la base.")
#---
# Qué hace: toma el mejor combo de la tabla, la compara contra la base
#           con el bootstrap pareado y aplica la regla fijada:
#           se adopta solo si el IC95 bajo es positivo.
#Criterio: es la misma regla de las exp. i〜iii, asi los resultados son comparables.

Mejor en selección: B0+mezcla TF-IDF y emb | alpha = 1.5

Δ MRR vs base                0.016
IC95 bajo                    0.006
IC95 alto                    0.030
licitaciones que mejoran    55.000
que empeoran                19.000
iguales                     56.000
dtype: float64

Se adopta en prueba.

In [36]:
#34#
#PRUEBA -hora de la verdad- 👁

if ganadora_emb:
    sc_pru_emb = puntuar_emb(pru)
    sc_pru_v = sc_pru_emb if nombre == "B0+embeddings" else mezclar(sc_pru, sc_pru_emb, 0.5)
    print("MRR base :", round(mrr_de(sc_pru, alpha_elegido, pru), 3))
    print("MRR nueva:", round(mrr_de(sc_pru_v, alpha_emb, pru), 3))
    display(pd.Series(comparar(sc_pru_v, alpha_emb, sc_pru, alpha_elegido, pru)).round(3))
else:
    print("Experimentación v: no se mide nada nuevo en prueba; el resultado reportado sigue siendo el de la Experimentación i.")

#----
# si en #33 hubo ganadora, la mide en 2024S1 contra la base. Si no, no mide nada.
#la prueba se usa una vez y solo con la ganadora, para no ajustar nada mirando 2024.

MRR base : 0.112
MRR nueva: 0.11

Δ MRR vs base               -0.002
IC95 bajo                   -0.024
IC95 alto                    0.022
licitaciones que mejoran    12.000
que empeoran                11.000
iguales                     34.000
dtype: float64

In [43]:
#35#
# desglose por S_inc y S_new

def desglose(sc, a, lics):
    g = gan[gan.id.isin(lics.id)]
    rk = ranking_de(sc, a)
    rk = rk[rk.id.isin(set(g.id))]
    rk0 = rk_b0_todo[rk_b0_todo.id.isin(set(g.id))]
    return ev.evaluar(rk, lic, emp, g, rk0)

sc_pru_mixemb = mezclar(sc_pru, sc_pru_emb, 0.5)

columnas = ["conjunto", "N", "MRR", "B0 MRR", "Δ MRR", "Δ MRR IC95", "Hit@5", "B0 Hit@5"]
casos = [("selección 2023", sel, sc_sel, sc_sel_mixemb),
         ("prueba 2024S1", pru, sc_pru, sc_pru_mixemb)]

partes = []
for etapa, lics, sc_base, sc_mix in casos:
    for metodo, sc, a in (("B0+TF-IDF (base)", sc_base, alpha_elegido),
                          ("B0+mezcla TF-IDF y emb", sc_mix, alpha_emb)):
        t = desglose(sc, a, lics)[columnas].copy()
        t.insert(0, "método", metodo)
        t.insert(0, "etapa", etapa)
        partes.append(t)

tabla_desglose = pd.concat(partes, ignore_index=True)
with pd.option_context("display.width", 250, "display.max_columns", None,
                       "display.float_format", "{:.3f}".format):
    display(tabla_desglose)
#---
# Qué hace: repite la medición separando las licitaciones en dos grupos, según lo que hace B0 con ellas:
#           S_inc (B0 pone a un ganador entre sus 10 primeros) y S_new (el resto).
#           Para cada grupo compara dos métodos contra B0: la base (B0+TF-IDF) y la mezcla con embeddings.
# Criterio: el promedio total puede esconder que un método ayuda en un grupo y perjudica en el otro.
#           Mostramos selección (2023) y prueba (2024S1), con el mismo intervalo de confianza de siempre.

             etapa                  método           conjunto    N   MRR  B0 MRR  Δ MRR        Δ MRR IC95  Hit@5  B0 Hit@5
0   selección 2023        B0+TF-IDF (base)              todas  130 0.142   0.125  0.017  (-0.010, +0.047)  0.269     0.246
1   selección 2023        B0+TF-IDF (base)  S_inc (B0 top-10)   41 0.346   0.361 -0.015  (-0.074, +0.053)  0.659     0.780
2   selección 2023        B0+TF-IDF (base)   S_new (el resto)   89 0.048   0.016  0.032  (+0.007, +0.064)  0.090     0.000
3   selección 2023  B0+mezcla TF-IDF y emb              todas  130 0.159   0.125  0.034  (+0.002, +0.070)  0.285     0.246
4   selección 2023  B0+mezcla TF-IDF y emb  S_inc (B0 top-10)   41 0.354   0.361 -0.007  (-0.065, +0.063)  0.683     0.780
5   selección 2023  B0+mezcla TF-IDF y emb   S_new (el resto)   89 0.068   0.016  0.052  (+0.017, +0.094)  0.101     0.000
6    prueba 2024S1        B0+TF-IDF (base)              todas   57 0.112   0.091  0.021  (-0.008, +0.056)  0.228     0.228
7    prueba 2024S1        B0+TF-IDF (base)  S_inc (B0 top-10)   16 0.304   0.294  0.010  (-0.079, +0.128)  0.688     0.812
8    prueba 2024S1        B0+TF-IDF (base)   S_new (el resto)   41 0.037   0.011  0.026  (+0.005, +0.051)  0.049     0.000
9    prueba 2024S1  B0+mezcla TF-IDF y emb              todas   57 0.110   0.091  0.020  (-0.023, +0.068)  0.211     0.228
10   prueba 2024S1  B0+mezcla TF-IDF y emb  S_inc (B0 top-10)   16 0.301   0.294  0.007  (-0.130, +0.181)  0.562     0.812
11   prueba 2024S1  B0+mezcla TF-IDF y emb   S_new (el resto)   41 0.036   0.011  0.024  (+0.005, +0.049)  0.073     0.000

## Conclusion del desglose por S_inc y S_new (Experimentación v).

Separamos las licitaciones según lo que hace B0: S_inc (B0 pone un ganador entre sus 10 primeros) y S_new (el resto). El texto mejora de forma consistente en S_new: Δ MRR = +0,032 en selección y +0,026 en prueba, con IC95 positivos en ambas etapas (en prueba, N = 41). En S_inc el MRR no cambia de forma medible, pero el Hit@5 baja (en prueba, de 0,812 a 0,688 con B0+TF-IDF y a 0,562 con la mezcla; N = 16), porque el texto desplaza algunos ganadores que B0 tenía arriba. La mezcla con embeddings no supera a B0+TF-IDF en S_new en prueba (+0,024 contra +0,026). Como los grupos se definen con el resultado de B0, la mejora en S_new es en parte esperable;

el hallazgo : es que el texto recupera ganadores nuevos, a costa de algo de precisión arriba del ranking.

In [44]:
import os, base64
from google.colab import userdata
%cd /content/grupo_Luabre

seccion = """

### Experimentación v: desglose por S_inc y S_new

S_inc = licitaciones donde B0 pone un ganador en su top-10; S_new = el resto.
Δ MRR es contra B0, con IC95 por bootstrap pareado.

| etapa | método | conjunto | N | MRR | B0 MRR | Δ MRR | IC95 | Hit@5 | B0 Hit@5 |
|---|---|---|--:|--:|--:|--:|---|--:|--:|
| selección 2023 | B0+TF-IDF | todas | 130 | 0.142 | 0.125 | +0.017 | (-0.010, +0.047) | 0.269 | 0.246 |
| selección 2023 | B0+TF-IDF | S_inc | 41 | 0.346 | 0.361 | -0.015 | (-0.074, +0.053) | 0.659 | 0.780 |
| selección 2023 | B0+TF-IDF | S_new | 89 | 0.048 | 0.016 | +0.032 | (+0.007, +0.064) | 0.090 | 0.000 |
| selección 2023 | mezcla TF-IDF y emb | todas | 130 | 0.159 | 0.125 | +0.034 | (+0.002, +0.070) | 0.285 | 0.246 |
| selección 2023 | mezcla TF-IDF y emb | S_inc | 41 | 0.354 | 0.361 | -0.007 | (-0.065, +0.063) | 0.683 | 0.780 |
| selección 2023 | mezcla TF-IDF y emb | S_new | 89 | 0.068 | 0.016 | +0.052 | (+0.017, +0.094) | 0.101 | 0.000 |
| prueba 2024S1 | B0+TF-IDF | todas | 57 | 0.112 | 0.091 | +0.021 | (-0.008, +0.056) | 0.228 | 0.228 |
| prueba 2024S1 | B0+TF-IDF | S_inc | 16 | 0.304 | 0.294 | +0.010 | (-0.079, +0.128) | 0.688 | 0.812 |
| prueba 2024S1 | B0+TF-IDF | S_new | 41 | 0.037 | 0.011 | +0.026 | (+0.005, +0.051) | 0.049 | 0.000 |
| prueba 2024S1 | mezcla TF-IDF y emb | todas | 57 | 0.110 | 0.091 | +0.020 | (-0.023, +0.068) | 0.211 | 0.228 |
| prueba 2024S1 | mezcla TF-IDF y emb | S_inc | 16 | 0.301 | 0.294 | +0.007 | (-0.130, +0.181) | 0.562 | 0.812 |
| prueba 2024S1 | mezcla TF-IDF y emb | S_new | 41 | 0.036 | 0.011 | +0.024 | (+0.005, +0.049) | 0.073 | 0.000 |

- El texto mejora en S_new de forma consistente (IC95 positivo en selección y en prueba).
- En S_inc el MRR no cambia de forma medible, pero el Hit@5 baja (en prueba N = 16).
- La mezcla con embeddings no supera a B0+TF-IDF en S_new en prueba (+0.024 contra +0.026).
- Los grupos se definen con el resultado de B0: la mejora en S_new es en parte esperable
  y no se puede usar el grupo para decidir al predecir.
"""
previo = open("resultados.md", encoding="utf-8").read()
if "Experimentación v: desglose por S_inc y S_new" in previo:
    print("Ya estaba la sección, no se agregó nada.")
else:
    with open("resultados.md", "a", encoding="utf-8") as f:
        f.write(seccion)
    print("Sección agregada.")

tok = userdata.get("GH_TOKEN")
h = base64.b64encode(f"x-access-token:{tok}".encode()).decode()
!git add resultados.md
!git status --short
!git commit -m "Experimentación v: desglose por S_inc y S_new"
!git -c http.extraheader="Authorization: Basic {h}" push origin main
!git status -sb | head -1

/content/grupo_Luabre
Sección agregada.
M  resultados.md
[main 99516f3] Experimentación v: desglose por S_inc y S_new
 1 file changed, 27 insertions(+)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.10 KiB | 282.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/AbiFrei/grupo_Luabre.git
   c6b4aa4..99516f3  main -> main
## main...origin/main